language: php
php:
  - "5.6"

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
 # - phpunit UnitTest unittests/AddTest.php
 - phpunit UnitTest unittests/LoginTest.php
 - phpunit UnitTest unittests/ssubcategoryTest.php

 - phpunit UnitTest unittests/SearchbarTest.php
 - phpunit UnitTest unittests/subcategoryTest.php
 - phpunit UnitTest unittests/categoryTest.php
 - phpunit UnitTest unittests/EditProfileTest.php


matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true

notifications:
  on_success: never
  on_failure: always
