language: php
php:
  - "5.6"

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: 
 - phpunit UnitTest unittests/AddTest.php
 - phpunit UnitTest unittests/LoginTest.php
 - phpunit UnitTest unittests/subcategoryTest.php
 - phpunit UnitTest unittests/categoryTest.php

matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true

notifications:
  on_success: never
  on_failure: always
