language: php
php:
  - "5.6"

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit AddTest
script: phpunit LoginTest

matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true

notifications:
  on_success: never
  on_failure: always